# Generated by Django 5.1 on 2024-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('todobucketid', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
